language: node_js
node_js:
  - "8"
  - "10"
  - "12"
script:
  - npx eslint lib/**/*.js test-lib/**/*.spec.js
  - npx lab -I regeneratorRuntime,Observable,__core-js_shared__,core,System,_babelPolyfill,asap -S -r console -m 4000 -o stdout -r lcov -o coverage.info -c --coverage-path lib 'test-lib'
  - cat coverage.info | ./node_modules/.bin/coveralls
